### ISSUE TITLE
 Couldn't find module: ti.fabric for architecture: x86_64

### ISSUE THREAD

**Issue by felipemathies** [mano-mykingdom/crashlytics#3]
hi man, first thanks for this awesome plugin....
so when im trying to run the app im having this error:
[ERROR] :  Script Error Couldn't find module: ti.fabric for architecture: x86_64

any clue what im doing wrong? i added the plugin folder, and plugin tag on tiapp.xml, and im loading the module like this : 
var Fabric = require("ti.fabric");

thanks!

**Comment by manojdcoder** [comment]
Hope you got the module files copied to your project's modules folder & added them under `<modules>` tag of `tiapp.xml`. May I know which version of Titanium SDK you are using?

**Comment by felipemathies** [comment]
which exactly files/folder i need to copy to my modules folder? im using 5.2.2.GA

**Comment by manojdcoder** [comment]
It is just same as installing other modules in Titanium. iOS module is located [here](https://github.com/mano-mykingdom/fabric/blob/master/iphone/dist/ti.fabric-iphone-1.0.zip)

**Comment by felipemathies** [comment]
thanks now its working, i don't know why i tought the plugin script was instilling the module for me, but one thing that im noticing is that titanium capture all the exceptions on production, not handling to frabic, do you now anything about that? thanks again....

**Comment by manojdcoder** [comment]
The plugin is to add fabric scripts to Xcode project once it is created, during build process. Use `Fabric.Crashlytics.logException` to log handled exceptions catch through [uncaughtException](http://docs.appcelerator.com./platform/latest/#!/api/Titanium.App-event-uncaughtException) event.

**Comment by felipemathies** [comment]
i put a listener on uncaughtException event, but when i try to call Fabric.Crashlytics.logException is undefined, i looked on Crashlytics.h and didn't found this method there, im on iOS it seems that this method is android only, do you have any clue how to do this on ios?

**Comment by manojdcoder** [comment]
Sorry, my bad. That method is not available on iOS, use `Fabric.Crashlytics.leaveBreadcrumb` or `Fabric.Crashlytics.setObject` to log exception details.

**Comment by felipemathies** [comment]
cool, i will test that out...tanks!

**Comment by parnanzio** [comment]
Where is the zip file for the iOS module? I cannot find it and the link above is not working: https://github.com/manojdcoder/fabric/blob/master/iphone/dist/ti.fabric-iphone-1.0.zip

```
parnanzio$ gittio install ti.fabric
[INFO]  ti.fabric searching...
[ERROR] ti.fabric:commonjs no distributable available
[ERROR] ti.fabric:ios no distributable available
```

**Comment by manojdcoder** [comment]
@parnanzio The module was recently updated by @chrisribe I have requested him to add the binaries. You may wait or just go ahead and compile locally on your machine.

**Comment by parnanzio** [comment]
@manojdcoder I just compiled it by myself.. It's working, thank you
