### ISSUE TITLE
tiapp.xml example no build

### ISSUE THREAD

**Issue by chrisribe** [mano-mykingdom/crashlytics#4]
Why is there no BuildSecret key in the main readme ?
I added it to my project and was able to get data into fabric.io

I found the config example from this project https://github.com/k0sukey/ti-fabric-hook
Looks like this project but do not know if it's related.

```
        <dict>
            <key>Fabric</key>
            <dict>
                <key>APIKey</key>
                <string>xxxxxxx</string>
                <key>BuildSecret</key>
                <string>yyyyyy</string>
                <key>Kits</key>
                <array>
                    <dict>
                        <key>KitInfo</key>
                        <dict>
                        </dict>
                        <key>KitName</key>
                        <string>Crashlytics</string>
                    </dict>
                </array>
            </dict>
        </dict>
```

Chris

**Comment by manojdcoder** [comment]
`BuildSecret` need not to be added under `info.plist`, at least till last time I used Crashlytics (more than 6 months ago).`BuildSecret` is only required during build process, will be added to Xcode build scripts through [hook](https://github.com/mano-mykingdom/fabric/blob/master/plugins/ti.fabric/cli/hooks/run.js).
