### ISSUE TITLE
Can this project log events to Fabric "Answers" ?

### ISSUE THREAD

**Issue by chrisribe** [mano-mykingdom/crashlytics#5]
Hi great project,

I need to log purchase events into Fabric Answers, can I use the [logEvent ](https://github.com/mano-mykingdom/fabric/blob/77fcadc37ce97e34ae95be54195d4a1ac3057506/iphone/platform/Crashlytics.framework/Headers/Crashlytics.h)function ?

It is marked as beta, but can I use it to build the proper event structure that Fabric is expecting ?

Answers.logPurchaseWithPrice(13.50,
    currency: "USD",
    success: true,
    itemName: "Answers Shirt",
    itemType: "Apparel",
    itemId: "sku-350",
    customAttributes: [:])

Thanks

**Comment by manojdcoder** [comment]
Sorry, it won't. This module was developed a year ago, has to be updated.

**Comment by chrisribe** [comment]
I would like to try and update it but have never done this type of thing. I know my way around xcode and appcelerator etc but... Do you have some pointers or links I could look at to get me started ?

Thanks
Chris
