### ISSUE TITLE
Android integration - status + remaining issues

### ISSUE THREAD

**Issue by davidcyp** [mano-mykingdom/crashlytics#9]
Hi there,

I have seen that some effort has already been done to integrate Android. Can you document what holds you back to finish this Android implementation. Once this is clear it becomes easier for the community to help finish this implementation.

**Comment by manojdcoder** [comment]
@davidcyp Titanium uses it's won build scripts (not sure about the latest version, but at least it was the case when I started with this module) where Fabric supports integration using Ant, Gradle, and Maven only.
